### ISSUE TITLE
Feature idea: copyright line in footer

### ISSUE THREAD

**Issue by DoctorD90** [daattali/beautiful-jekyll#847] opened 2021-08-09 07:53 UTC
The source code of the site is released under the MIT license, but the contents created by authors/owners of each site could be copyrighted under different license than MIT.
Would be possible to add in the footer a simple span/div (configurable from `_config.yml` maybe) with the desired license? (example: Creative Commons). I dont aim to have a full list of pre-configured licenses (it would be awesome), but a simple `copyright.html` where users can paste their html lines and it will be included in the footer automatically.
Moreover the link to the license page (if present) in the footer should be "underlined" and in "link color".

***To do:***
- Create a `copyright.html` where users are able to paste their simple lines (created automatically by many sites)
- Include, if exists, the `copyright.html` in the footer

***Nice to have:***
- A list in the `_config.yml` with a list of presetted available licenses
- As for "share buttons", a precise div, with the possibility to include a licenses at the ends of articles/pages/an include commands for licenses.

**Comment by daattali** [comment] 2021-08-09 16:17
I would strongly prefer not to create an additional file that *must* exist, so of the license file is optional that would be ok. However, as far as I know there is no way to check for the existence of a file with jekyll and have conditional rendering logic based on whether the file exists. 

This is the closest thing
https://jekyllrb.com/docs/static-files/ but it only works on purely static files with no frontmatter

**Comment by DoctorD90** [comment] 2021-08-11 10:43
I thought about it.
What about to create a variable in the `_config.yml` or a simple empty `_includes/copyrigth.html` and leave people to fill it? In this way you can preconfigure the html layout in the `_includes/footer.html` and people can call it with an `include` in their posts if they want.
For my purposes I added a span in the footer, but im not really an html/css expert, so it looks nice but Im pretty sure there is a better html/css way. If you want I can share it.

**Comment by daattali** [comment] 2021-08-12 00:52
There is already a 'footer-extra' parameter, which allows you to specify an HTML file to include in the footer. It sounds very similar to what you suggest. Would that work for your purposes?

**Comment by DoctorD90** [comment] 2021-08-23 16:56
Thanks for patience! I tried it. It seems doesnt work.
- I created a file footer-license.html
- I added "footer-extra: "footer-license.html" to the _config.yml
- Rebuild the site cleaning the cache

Nothing appeared

**Comment by daattali** [comment] 2021-08-23 19:14
It's a YAML parameter (per-page parameter), not a global (config file) parameter.

If you want to apply it to all pages, you can use the `defaults` in the config file.

I'm closing this issue as it's not a bug and it will not be added as a new feature. If you are having trouble figuring out how to use a feature (like footer-extra) you can look at other sites using them. My personal website example uses it.

**Closed by daattali** 2021-08-23 19:14 UTC
