### ISSUE TITLE
beautiful-jekyll gem supported by GitHub pages

### ISSUE THREAD

**Issue by sumitgpt** [daattali/beautiful-jekyll#237] opened 2017-08-27 08:59 UTC
When using beautiful-jekyll-theme as a gem one has to add "theme: beautiful-jekyll-theme" in _config.yml
This results in an error from GitHub. Below is the error which is emailed by GitHub when using this theme in GitHub pages.

> You are attempting to use a Jekyll theme, "beautiful-jekyll-theme", which is not supported by GitHub Pages

Can support of this theme be added to GitHub pages?

**Comment by daattali** [comment] 2017-08-27 16:19
Github page only supports very few themes, listed here https://pages.github.com/themes/

I've had many people ask me about this so maybe I'll ask github if my theme can also be added at some point

**Comment by sumitgpt** [comment] 2017-08-27 16:43
Thank you,
I hope they do add your theme to the list. I've to maintain branches to make it work on GitHub pages, it's a pain.

Also, can you let this issue be open and update the progress here?

**Comment by daattali** [comment] 2017-08-27 18:30
Sure, I doubt github will support it because there are only ~10 supported
themes, but we'll keep it open. Perhaps if over time more people find this
issue and upvote, it might be possible. Thanks for opening the issue!

**Comment by ohadschn** [comment] 2017-08-28 23:40
While this isn't supported directly using GitHub's engine, it can be achieved by executing the Jekyll build yourself (e.g. [using Travis CI](https://4brunu.github.io/blog/2017/01/29/using-jekyll-gem-based-themes-on-github-pages)). 

Another option is using Git**Lab** pages, just fork this and you should be able to use any gem-based theme: https://gitlab.com/pages/jekyll. For example here's mine, using minimal mistakes: https://gitlab.com/ohadschn/ohadschn.gitlab.io.

BTW @daattali the latest gem I see on RubyGems is from December:
https://rubygems.org/gems/beautiful-jekyll-theme

**Comment by daattali** [comment] 2017-08-29 06:22
Toda Ohad, I wasn't aware of the Travis solution, good to know.

The gem is indeed a bit old, I'll update it when I get a chance :)

**Comment by daattali** [comment] 2017-09-06 17:45
as mentioned in #243, I've decided to stop supporting the gem for now (it's a lot more work for everyone while being less flexible and has some other issues). If it can ever become a supported github pages gem, then it would be worth continuing supporting it because it would remove all the issues it currently has and will be easy to use again.

**Comment by daattali** [comment] 2020-04-02 06:19
This is a duplicate of https://github.com/daattali/beautiful-jekyll/issues/339 , which has a work-in-progress PR

**Closed by daattali** 2020-04-02 06:19 UTC
