### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by fkarg** [daattali/beautiful-jekyll#637] opened 2020-05-15 23:28 UTC
So I recently found out how to add footnotes, it was recommended to do them like this:

```
Footnote<sup>[1](#footnote1)</sup> among text.

---
#### Footnotes

<a name="footnote1">1</a>: Text from footnote1.
```

And while it works, when clicking on the footnote it jumps _just a bit_ too low, probably because it is not aware of the additional header. Is there a way to make that somehow smarter?

I'd prefer a 'Footnote'-system similar to the one in LaTeX, where I don't need to explicitly track the numbers, but this is probably asking for too much. If anyone knows something, let me know though!

Please just close this issue if it has been fixed already - I did not read anything about it in the changelog, but I haven't upgraded to v3 yet.

**Comment by daattali** [comment] 2020-05-15 23:42
I believe this is a duplicate of #69 

The new version from the past month fixes this. If you have an older version you can look at that discussion

**Closed** 2020-05-17 20:54 UTC

**Comment by fkarg** [comment] 2020-05-18 16:33
Awesome, thanks!
