### ISSUE TITLE
Content does not seem to go full width?

### ISSUE THREAD

**Issue by catches** [daattali/beautiful-jekyll#1117] opened 2023-03-23 17:22 UTC
So I have content in my style.css file, and I have full-width set to true in my html file, but when I adjust the `width: rem;` or `height:rem;` in style.css, it doesn't seem to change properly and it still constrains it, I want it to fill the empty space.

```
{
  margin: 0; padding: 0;
  box-sizing: border-box;
}

.video-container{
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

.video-container .video{
  height:15rem;
  width: 20rem;
  margin:1rem;
  box-shadow: 0 .5rem 1rem rgba(0,0,0,0.5);
  overflow: hidden;
  border-radius: 1rem;
}

.video-container .video video{
  height:100%;
  width:100%;
  object-fit: cover;
  outline: none;
  border: none;
  cursor: pointer;
}
```
```
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/assets/css/style.css">
  </head>

  <body>

    <div class="container">

      <div class="video-container">

        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>

        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>

        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>
        
        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>

        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>

        <div class="video">
          <iframe src="https://youtube.com/embed/tUQwKpzFIjY?feature=share" width="100%" height="100%" style="border: 0" allowfullscreen></iframe>
        </div>

      </div>

    </div>

  </body>

</html>
```

</html>

**Comment by daattali** [comment] 2023-03-24 04:55
Hi, I appreciate your interest in this theme! However, in order to ensure we best utilize this space, we try to only post bugs or feature requests here. This question is not really about an issue in beautiful jekyll, it sounds more like a private issue/ask for help. In that case there are many forums online where you can ask for help with your jekyll site. I'm going to close this issue since it's not a bug report.

**Closed by daattali** 2023-03-24 04:55 UTC
