### ISSUE TITLE
How would I change the order of icons at the bottom of the page?

### ISSUE THREAD

**Issue by michael-b-jordan** [daattali/beautiful-jekyll#1152] opened 2023-06-11 15:40 UTC
For example this,
![image](https://github.com/daattali/beautiful-jekyll/assets/129551266/e3b5f662-cc19-4fb7-84c6-82308b2347ce)

Currently, it goes like Email, Telegram, and Discord, but what if I want the order to be Discord, Telegram, and Email.

**Comment by daattali** [comment] 2023-06-11 20:04
Duplicate of https://github.com/daattali/beautiful-jekyll/issues/757

I'll think if there's a good simple way to implement this

**Comment by daattali** [comment] 2023-06-11 23:37
If you use the newest unreleased version, you can now manipulate the order by changing the order of the fields in the config file.

**Closed** 2023-06-11 23:36 UTC
