### ISSUE TITLE
Posts for 2021????

### ISSUE THREAD

**Issue by pavelsg** [daattali/beautiful-jekyll#920] opened 2021-12-21 05:05 UTC
Am I doing something wrong or it just doesn't work for 2021 posts? :)
Simply trying to rename 2020-02-28-test-markdown.md to 2021-02-28-test-markdown.md removes post from the index/blog (page doesn't get generated)

**Comment by daattali** [comment] 2021-12-21 10:25
This shouldn't be an issue. Please link to the file in your github repository and to your website

**Comment by pavelsg** [comment] 2021-12-22 10:14
Sure, but will try to reproduce using clean repo first.

**Comment by tillgrallert** [comment] 2022-01-04 18:28
Just stumbled across a similar problem. As soon as I set the date in a post's YAML to 2022, eg. today's "2022-01-04", the date is duplicated in the post's URL (i.e. "2022-01-04-2022-01-04-{filename}.md") and title and subtitle are removed from the output. In addition, the post has no title, subtitle, summary or tags on the blog's landing page. For an example see <https://openarabicpe.github.io/>

**Comment by tillgrallert** [comment] 2022-01-04 21:52
After some digging around in the new build workflow in the Github Actions menu, I saw that my text editor had faultily added tab-stops instead of spaces in front of the tags in the YAML frontmatter. Once I replace them, the issue was solved.

**Comment by daattali** [comment] 2022-01-05 09:13
I'm closing this issue as it's not reproducible. I believe if anone is having an issue with the date, they're probably doing something wrong with jekyll. I just tried it on my own and everything seems to be working fine.

**Closed by daattali** 2022-01-05 09:13 UTC
