### ISSUE TITLE
staticman comments do not show in post

### ISSUE THREAD

**Issue by fancyerii** [daattali/beautiful-jekyll#460] opened 2019-02-09 18:14 UTC
I found comments are added in _data/comments/post-name/comment-xxx.yaml. But In the post I can't see the comment. What's wrong?

**Comment by daattali** [comment] 2019-02-09 20:13
@VincentTam might be able to help

**Comment by VincentTam** [comment] 2019-02-09 20:18
Yes, it does show up.  You may check the GitHub Page.  Please feel free to ping me for any questions.

**Comment by VincentTam** [comment] 2019-05-21 16:53
@daattali Please consider closing this issue because

1. I've tried to reproduce the reported behavior.

       $ git clone git@github.com:VincentTam/fancyerii.github.io.git
       # checkout last commit created by Staticman, and create a gh-branch from there
       $ git log --author "Staticman Lab" --pretty="%h" | xargs git checkout
       $ git checkout -b gh-pages
       $ git push -u origin gh-pages

    However, I got the _opposite_ conclusion from [my clone of @fancyerii's clone](https://vincenttam.github.io/fancyerii.github.io/2015-02-28-test-markdown/), and
2. OP has switched theme.

**Comment by daattali** [comment] 2019-06-07 04:42
Thanks @VincentTam

**Closed by daattali** 2019-06-07 04:42 UTC
