### ISSUE TITLE
webpage can not show the images with bigimg

### ISSUE THREAD

**Issue by weiguangcui** [daattali/beautiful-jekyll#294] opened 2017-12-28 20:12 UTC
Dear

Thank you so much for sharing this beautiful theme!
I tried to include some images in my aboutme.md file (weblink: https://weiguangcui.github.io/aboutme/). The website reports no error, but these images can not show up in that page. Also, there are some images with bigimg can be shown in the main page https://weiguangcui.github.io, some are not!
Is it a problem of my images? If so, what format should it be? If not, how can I correct that?

One, last thing, is it possible to include the image by 100% height not 100% width for these images included with bigimg.

Thanks a lot!

Best,
Weiguang

**Comment by daattali** [comment] 2017-12-28 21:39
For the images not showing up, I'm not sure what the problem is, you'd have
to look at the ones that work and the ones that don't, and try to compare
to see what the difference is in the URL. I haven't heard of any such
reports so I assume it's something with your URLs. Perhaps you need to add
a slash "/" to the beginning of the image url. As for the height vs width,
you can change that in the css/main.css file (you would need to know some
basic css)

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by weiguangcui** [comment] 2017-12-28 22:19
Thank you for the suggestions. Yes, it is the problem of the slash...
I have no idea of css, could you possibly give me some hints of where and how to change?
I have tried without setting width, and with padding-top, but none works...
Thanks again

**Comment by daattali** [comment] 2017-12-28 22:41
Sorry, giving individual css tips is out of scope. I do suggest taking a
few hours to go through css tutorials if you want to do any customizations,
it'll benefit you a lot

**Closed** 2017-12-29 17:59 UTC
