### ISSUE TITLE
Post preview shows markdown

### ISSUE THREAD

**Issue by thejcannon** [daattali/beautiful-jekyll#1322] opened 2024-05-27 12:08 UTC
👋 I'm trying out Beautiful Jekyll for a site and noticed that my post, which starts with a markdown code block is rendered quite literally in the home pages summary (E.g. the summary starts with "\`\`\`text")

(Also love it so far, thanks for making this ❤️)

**Comment by daattali** [comment] 2024-05-27 19:28
This is unfortunately working "as intended". It's not really an issue specific to this theme, it's a more general jekyll concern. I'm going to close this issue since it's not a bug with my theme, but I'll try to walk you through what's happening, so that you can try to think of a custom solution or take this info and ask in a jekyll forum about work arounds:

Jekyll has the concept of a "post excerpt" as described here https://jekyllrb.com/docs/posts/#post-excerpts and as you can see, by default it takes the **first paragraph of content**. Here if the code in beautiful jekyll that takes this excerpt and shows it on the home page: https://github.com/daattali/beautiful-jekyll/blob/b57d3d4a4abd3027edc8c39e2749a57b53f9a5e2/_layouts/home.html#L75-L76

So what's happening is that because you have a blank line inside that (poem?), jekyll treats that as a new paragraph. So it takes all the content up until that blank line, which is:

````
```text
It is a period of civil war.
Rebel collectors, striking
from a hidden basement,
have won their first victory
against the evil Garbage Empire.
````

And this it the post excerpt (if you use the `excerpt_length` parameter that beautifuljekyll uses, then it'll truncate the number of words). When you take the text above, jekyll does not know that this is markdown because it doesn't see the closing backticks. So it thinks the opening ticks are part of the text.

To drive this point further, I think (I haven't tested this) that if you remove blank lines from the poem, or if you ended the markdown syntax after the first paragraph, then the post excerpt on the home page will look correct. 

You can also explicitly define what the excerpt should be, by adding a `excerpt:` YAML field in the post. On the jekyll documentation page that I linked above, you may have noticed that they talk about a `excerpt_separator`, perhaps you can use that so that the blank line doesn't end the excerpt.

I hope this was useful.

**Closed by daattali** 2024-05-27 19:28 UTC

**Comment by thejcannon** [comment] 2024-05-27 21:05
Oh wow that's a very thorough response! That all makes perfect sense, I'll play around with some settings, thanks!
