### ISSUE TITLE
New posts do not reflect in my blog

### ISSUE THREAD

**Issue by haor1** [daattali/beautiful-jekyll#992] opened 2022-05-26 22:39 UTC
I am reporting a bug. I have added a new post to my blog as I usually do (same formatting and everything), however, the new post is not reflecting on my blog. Usually a new post appears after a few minutes. It has been several hours and it is not appearing. Is something broken?

https://github.com/haor1/haor1.github.io/tree/master/_posts

**Comment by daattali** [comment] 2022-05-26 23:11
If all previous posts worked and for some reason a new post isn't showing up, that generally means either you did something wrong or there's a bug in jekyl. Not in the theme. It's likely that you just did something that isn't correct. For example if you created a post with  a future date. I'm closing this issue because this doesn't sound like a bug in the theme.

If you still think there's a bug in the theme please open a new issue and include exact reproducible steps.

**Closed by daattali** 2022-05-26 23:11 UTC
